Controllers films users
airkng/java-filmorate pull request #2
Opened 2023-03-07 19:03 UTC by airkng

ТЗ-9. Создание и установка контроллеров, классов User и Film, тестирование

2023-03-07 20:37 UTC, TomattmanYandex requested changes
Привет, сделано хорошо, но всякие мелочи надо поправить

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +     * Я считаю, надо создать петицию, чтобы всех PM-ов уволили и вообще удалили такую профессию и оставить бэкендеров
Кто то должен общаться с клиентами, и получать все шишки, так что пусть будут

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        List<Film> filmsList = new ArrayList<>();
почему бы не сделать просто return films.values();

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @PostMapping()
А зачем пустые скобки оставлять?

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (films.containsKey(film.getId()) || films.containsValue(film)) {
обычно пост запрос это в любом случае создать, поэтому я бы рекомендовал тут проставить новый id и сохранять
но если хочешь сохранить уникальность фильмов то норм

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +            throw new ValidateException("Объект " + film + " уже существует. Воспользуйтесь методом PUT");
только 
то будет не ошибка валидации а какая нибудь другая

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        Film newFilm = film.toBuilder()
вариант рабочий, но почем не сделать film.setId() и дальше работать с одним объектом?

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        // Это всегда так, если исключение обрабатываешь, то статус 200 приходит в ответ? Я потому что попытался исправить
Это будет в следующем спринте, но обычно если просто обьект возвращаешь, то если все успешно то 200

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (films.containsKey(film.getId())) {
а put это обычно или изменёние, или вставка, если такого нету

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +public class UserController {
тут будет все то же самое что и в предыдущем классе

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User getAdminData() {
а вот этого в требованиях не было, так что стоит удалить)))

2023-03-07 20:37 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +     * Как там продвигается приложение?
дела хорошо, нового ничего, хотя ладно, на днях потеплело, приложение сделал версию, очень некрасивую, мне подкинули идею как его улучшить, и я пока что подзабил, но думаю потихоньку возвращаться к его реализации

2023-03-09 17:26 UTC, airkng commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        List<Film> filmsList = new ArrayList<>();
Оке, переделаю, что-то тупанул -_-

2023-03-09 17:38 UTC, airkng commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User getAdminData() {
.... Это фича, а не баг...

2023-03-09 19:23 UTC, airkng commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        if (films.containsKey(film.getId())) {
Если вставка, то тесты не проходит :( Тут видимо PUT только на замену работает

2023-03-10 09:53 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +    public User getAdminData() {
можно просто по умолчанию в данные добавить)))

2023-03-10 09:54 UTC, TomattmanYandex approved these changes
принято

2023-03-15 07:46 UTC, merged